AWSTemplateFormatVersion: '2010-09-09'
Description: >
  CloudFormation template for the AtenaDocs Artifacts Bucket.

  This template creates a single S3 bucket with a specific purpose: to store the
  build artifacts (packaged source code and dependency layers) that will be
  used by other CloudFormation stacks, such as `backend-dev-template.yaml`.

  Separating the creation of this bucket into its own template is a good practice because
  it is a bootstrap resource that rarely changes and is a prerequisite for
  deploying applications.

Resources:

  # --- S3 Bucket for Build Artifacts ---
  PdfMergeArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "adocs-pdf-merge-artifacts-${AWS::AccountId}-${AWS::Region}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Project
          Value: adocs
        - Key: Environment
          Value: Development
        - Key: Component
          Value: Backend-Artifacts
        - Key: ManagedBy
          Value: CloudFormation

# =============================================================================
# OUTPUTS
# =============================================================================
Outputs:
  BucketName:
    Description: "Name of the S3 bucket for the PDF merge service artifacts"
    Value: !Ref PdfMergeArtifactsBucket
