
AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Main infrastructure for AtenaDocs: S3 Bucket for PDFs, Python Lambda function
  for merging, an API Gateway, and an AWS Amplify app for CI/CD and hosting.

Parameters:
  EnvironmentName:
    Type: String
    Default: development
    AllowedValues: [development, production]
    Description: The environment name, which determines resource naming and behavior (e.g., error reporting).
  RepositoryUrl:
    Type: String
    Description: "Required: The full URL of the source code repository (e.g., https://github.com/username/reponame)."
  AccessToken:
    Type: String
    Description: "Required: A personal access token with 'repo' scope to connect Amplify to your Git repository."
  BranchName:
    Type: String
    Default: dev
    Description: "The Git branch that Amplify should build and deploy."

Conditions:
  IsProduction: !Equals [!Ref EnvironmentName, production]

Resources:
  # --- S3 Bucket for Storing PDF Files (User Uploads) ---
  PdfBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'atenadocs-pdf-merge-${EnvironmentName}-${AWS::AccountId}-${AWS::Region}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - POST
              - GET
              - PUT
            AllowedOrigins:
              - '*' # Allows direct browser uploads from any origin.
            ExposedHeaders:
              - ETag
            MaxAge: 3600
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: AtenaDocs

  # --- IAM Role for the Lambda Function ---
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: 'AtenaDocsS3AndLogsPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: 'arn:aws:logs:*:*:*'
              # Permissions for the Lambda to interact with the PDF bucket
              - Effect: Allow
                Action:
                  - 's3:GetObject'
                  - 's3:PutObject'
                  - 's3:DeleteObject'
                  - 's3:DeleteObjects'
                Resource: !Sub '${PdfBucket.Arn}/*'
              # This single s3:* permission on the bucket is what grants the ability
              # for the Lambda function's code to generate a pre-signed URL.
              # It is more secure than granting broad s3:GeneratePresignedUrl permissions.
              - Effect: Allow
                Action:
                  - 's3:GeneratePresignedUrl'
                Resource: !Sub '${PdfBucket.Arn}/*'

  # --- Lambda Layer for Python Dependencies ---
  PdfDependenciesLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: !Sub 'atenadocs-layer-pdf-merge-${EnvironmentName}'
      Description: "Dependencies for the AtenaDocs PDF merge function (PyPDF2, boto3)."
      Content:
        S3Bucket: !Sub 'atenadocs-artifacts-pdf-merge-${AWS::AccountId}-${AWS::Region}'
        S3Key: 'layer.zip'
      CompatibleRuntimes:
        - python3.13

  # --- The Lambda Function for PDF Merging ---
  PdfMergeFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'atenadocs-pdf-merge-${EnvironmentName}'
      Handler: 'lambda_function.lambda_handler'
      Runtime: 'python3.13'
      MemorySize: 256
      Timeout: 120
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !Sub 'atenadocs-artifacts-pdf-merge-${AWS::AccountId}-${AWS::Region}'
        S3Key: 'lambda_function.zip'
      Environment:
        Variables:
          S3_BUCKET_NAME: !Ref PdfBucket
          ENVIRONMENT_NAME: !Ref EnvironmentName
      Layers:
        - !Ref PdfDependenciesLayer
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: AtenaDocs
          
  # --- API Gateway (REST API) ---
  RestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub 'AtenaDocsApi-${EnvironmentName}'
      EndpointConfiguration:
        Types:
          - REGIONAL

  ApiMergeResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestApi
      ParentId: !GetAtt RestApi.RootResourceId
      PathPart: 'merge'

  ApiPostMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApi
      ResourceId: !Ref ApiMergeResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${PdfMergeFunction.Arn}/invocations"

  ApiOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApi
      ResourceId: !Ref ApiMergeResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        RequestTemplates:
          application/json: '{ "statusCode": 200 }'
        IntegrationResponses:
          - StatusCode: '200'
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'POST,OPTIONS'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
            ResponseTemplates:
              application/json: ""
      MethodResponses:
        - StatusCode: '200'
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true

  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - ApiPostMethod
      - ApiOptionsMethod
    Properties:
      RestApiId: !Ref RestApi
      # A new deployment is created every time the stack is updated.
      Description: !Sub 'Deployment for ${AWS::StackId}'

  ApiStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      StageName: 'dev'
      RestApiId: !Ref RestApi
      DeploymentId: !Ref ApiDeployment

  LambdaApiGatewayPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt PdfMergeFunction.Arn
      Action: 'lambda:InvokeFunction'
      Principal: 'apigateway.amazonaws.com'
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RestApi}/*'

  # --- AWS Amplify for Frontend CI/CD and Hosting ---
  AmplifyApp:
    Type: 'AWS::Amplify::App'
    Properties:
      Name: !Sub 'atenadocs-app-${EnvironmentName}'
      Repository: !Ref RepositoryUrl
      AccessToken: !Ref AccessToken
      Platform: WEB_COMPUTE # Crucial for Next.js SSR
      BuildSpec: |
        version: 1
        frontend:
          phases:
            preBuild:
              commands:
                - npm ci
            build:
              commands:
                - npm run build
          artifacts:
            baseDirectory: .next
            files:
              - '**/*'
          cache:
            paths:
              - node_modules/**/*
      # Pass the backend URL to the frontend build
      EnvironmentVariables:
        - Name: NEXT_PUBLIC_API_URL
          Value: !Sub "https://${RestApi}.execute-api.${AWS::Region}.amazonaws.com/dev/merge"
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: AtenaDocs

  AmplifyBranch:
    Type: 'AWS::Amplify::Branch'
    Properties:
      AppId: !GetAtt AmplifyApp.AppId
      BranchName: !Ref BranchName
      EnableAutoBuild: true
      Stage: !If [IsProduction, PRODUCTION, DEVELOPMENT]
      EnvironmentVariables:
        - Name: NEXT_PUBLIC_API_URL
          Value: !Sub "https://${RestApi}.execute-api.${AWS::Region}.amazonaws.com/dev/merge"

Outputs:
  PdfFilesS3BucketName:
    Description: "The name of the S3 bucket for storing user-uploaded PDF files."
    Value: !Ref PdfBucket
  ApiGatewayEndpoint:
    Description: "The public endpoint URL for the backend API."
    Value: !Sub "https://${RestApi}.execute-api.${AWS::Region}.amazonaws.com/dev/merge"
  AmplifyAppId:
    Description: "The ID of the Amplify application."
    Value: !GetAtt AmplifyApp.AppId
  AmplifyAppUrl:
    Description: "The default URL of the deployed Amplify application."
    Value: !Sub "https://${BranchName}.${AmplifyApp.DefaultDomain}"
