AWSTemplateFormatVersion: '2010-09-09'
Description: >
  (Robust) CloudFormation template for the AtenaDocs Frontend.
  This version explicitly sets the platform to WEB_COMPUTE to ensure Next.js (SSR) 
  support is enabled, preventing 404 errors by forcing the correct deployment environment.

Parameters:
  BackendApiUrl:
    Type: String
    Description: The full base URL of the backend API.
  RepositoryUrl:
    Type: String
    Description: The full HTTPS URL of the source code repository.
  GitHubOAuthToken:
    Type: String
    NoEcho: true
    Description: A GitHub Personal Access Token with 'repo' and 'admin:repo_hook' scopes.

Resources:
  AmplifyApp:
    Type: 'AWS::Amplify::App'
    Properties:
      Name: adocs-frontend-dev
      Description: AtenaDocs Frontend Application (Dev)
      Repository: !Ref RepositoryUrl
      OauthToken: !Ref GitHubOAuthToken
      Platform: WEB_COMPUTE # Explicitly sets the platform for SSR/Next.js
      # BuildSpec is omitted to allow Amplify to use its default, platform-aware build process.
      Tags:
        - Key: Project
          Value: adocs
        - Key: Environment
          Value: Development
        - Key: Component
          Value: Frontend
        - Key: ManagedBy
          Value: CloudFormation

  AmplifyDevBranch:
    Type: 'AWS::Amplify::Branch'
    Properties:
      AppId: !GetAtt AmplifyApp.AppId
      BranchName: dev
      Stage: DEVELOPMENT
      EnableAutoBuild: true
      Description: Development branch for the frontend.
      EnvironmentVariables:
        - Name: NEXT_PUBLIC_PDF_MERGE_API_URL
          Value: !Ref BackendApiUrl

Outputs:
  AmplifyAppId:
    Description: The ID of the Amplify App.
    Value: !GetAtt AmplifyApp.AppId
  DefaultDomain:
    Description: The default domain for the deployed 'dev' branch.
    Value: !Sub 'https://dev.${AmplifyApp.DefaultDomain}'
